name: Publish Docker Image
#DOCKER 
# This trigger runs the workflow every time you push to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Downloads a copy of your code to the runner
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Logs into Docker Hub using the secrets you saved earlier
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 3. Builds the image from your Dockerfile and pushes it to Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: sumayyahabeeba/event-management:latest
